package com.myspace.permitting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("HOA Date")
	private String hoaDate;
	@org.kie.api.definition.type.Label("HOA Address")
	private java.lang.String hoaAddress;
	@org.kie.api.definition.type.Label("HOA Representative")
	private java.lang.String hoaRepresentative;
	@org.kie.api.definition.type.Label("HOA Group")
	private java.lang.String hoaGroup;
	@org.kie.api.definition.type.Label("Application Status")
	private java.lang.String applicationStatus;

	@org.kie.api.definition.type.Label("Applicant")
	private com.myspace.permitting.Applicant applicant;

	@org.kie.api.definition.type.Label("HOA Approved")
	private java.lang.Boolean hoaApproved;

	@org.kie.api.definition.type.Label("Representative If Unassigned")
	private java.lang.String representativeIfUnassigned;

	@org.kie.api.definition.type.Label("Email Of Representative If Unassigned")
	private java.lang.String emailOfRepresentativeIfUnassigned;

	@org.kie.api.definition.type.Label(value = "Status Check Delay")
	private java.lang.String statusCheckDelay;

	public NewOrder() {
	}

	public java.lang.String getHoaAddress() {
		return this.hoaAddress;
	}

	public void setHoaAddress(java.lang.String hoaAddress) {
		this.hoaAddress = hoaAddress;
	}

	public java.lang.String getHoaRepresentative() {
		return this.hoaRepresentative;
	}

	public void setHoaRepresentative(java.lang.String hoaRepresentative) {
		this.hoaRepresentative = hoaRepresentative;
	}

	public java.lang.String getHoaGroup() {
		return this.hoaGroup;
	}

	public void setHoaGroup(java.lang.String hoaGroup) {
		this.hoaGroup = hoaGroup;
	}

	public java.lang.String getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(java.lang.String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public com.myspace.permitting.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(com.myspace.permitting.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.lang.String getHoaDate() {
		return this.hoaDate;
	}

	public void setHoaDate(java.lang.String hoaDate) {
		this.hoaDate = hoaDate;
	}

	public java.lang.Boolean getHoaApproved() {
		return this.hoaApproved;
	}

	public void setHoaApproved(java.lang.Boolean hoaApproved) {
		this.hoaApproved = hoaApproved;
	}

	public java.lang.String getRepresentativeIfUnassigned() {
		return this.representativeIfUnassigned;
	}

	public void setRepresentativeIfUnassigned(
			java.lang.String representativeIfUnassigned) {
		this.representativeIfUnassigned = representativeIfUnassigned;
	}

	public java.lang.String getEmailOfRepresentativeIfUnassigned() {
		return this.emailOfRepresentativeIfUnassigned;
	}

	public void setEmailOfRepresentativeIfUnassigned(
			java.lang.String emailOfRepresentativeIfUnassigned) {
		this.emailOfRepresentativeIfUnassigned = emailOfRepresentativeIfUnassigned;
	}

	public java.lang.String getStatusCheckDelay() {
		return this.statusCheckDelay;
	}

	public void setStatusCheckDelay(java.lang.String statusCheckDelay) {
		this.statusCheckDelay = statusCheckDelay;
	}

	public NewOrder(java.lang.String hoaDate, java.lang.String hoaAddress,
			java.lang.String hoaRepresentative, java.lang.String hoaGroup,
			java.lang.String applicationStatus,
			com.myspace.permitting.Applicant applicant,
			java.lang.Boolean hoaApproved,
			java.lang.String representativeIfUnassigned,
			java.lang.String emailOfRepresentativeIfUnassigned,
			java.lang.String statusCheckDelay) {
		this.hoaDate = hoaDate;
		this.hoaAddress = hoaAddress;
		this.hoaRepresentative = hoaRepresentative;
		this.hoaGroup = hoaGroup;
		this.applicationStatus = applicationStatus;
		this.applicant = applicant;
		this.hoaApproved = hoaApproved;
		this.representativeIfUnassigned = representativeIfUnassigned;
		this.emailOfRepresentativeIfUnassigned = emailOfRepresentativeIfUnassigned;
		this.statusCheckDelay = statusCheckDelay;
	}

}