package com.myspace.permitting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderPermit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("HOA Date")
	private String hoaDate;
	@org.kie.api.definition.type.Label("HOA Address")
	private java.lang.String hoaAddress;
	@org.kie.api.definition.type.Label("HOA Representative")
	private java.lang.String hoaRepresentative;
	@org.kie.api.definition.type.Label("HOA Group")
	private java.lang.String hoaGroup;
	@org.kie.api.definition.type.Label("REP Status")
	private java.lang.String repStatus;
	@org.kie.api.definition.type.Label("RSP Status")
	private java.lang.String rspStatus;
	@org.kie.api.definition.type.Label("Application Status")
	private java.lang.String applicationStatus;

	@org.kie.api.definition.type.Label("Applicant")
	private com.myspace.permitting.Applicant applicant;

	@org.kie.api.definition.type.Label("Status Check Delay")
	private java.lang.String statusCheckDelay;

	@org.kie.api.definition.type.Label("REP Id")
	private java.lang.String repId;

	@org.kie.api.definition.type.Label("RSP Id")
	private java.lang.String rspId;

	@org.kie.api.definition.type.Label(value = "HOA Approved")
	private java.lang.Boolean hoaApproved;

	public OrderPermit() {
	}

	public java.lang.String getHoaAddress() {
		return this.hoaAddress;
	}

	public void setHoaAddress(java.lang.String hoaAddress) {
		this.hoaAddress = hoaAddress;
	}

	public java.lang.String getHoaRepresentative() {
		return this.hoaRepresentative;
	}

	public void setHoaRepresentative(java.lang.String hoaRepresentative) {
		this.hoaRepresentative = hoaRepresentative;
	}

	public java.lang.String getHoaGroup() {
		return this.hoaGroup;
	}

	public void setHoaGroup(java.lang.String hoaGroup) {
		this.hoaGroup = hoaGroup;
	}

	public java.lang.String getRepStatus() {
		return this.repStatus;
	}

	public void setRepStatus(java.lang.String repStatus) {
		this.repStatus = repStatus;
	}

	public java.lang.String getRspStatus() {
		return this.rspStatus;
	}

	public void setRspStatus(java.lang.String rspStatus) {
		this.rspStatus = rspStatus;
	}

	public java.lang.String getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(java.lang.String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public com.myspace.permitting.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(com.myspace.permitting.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.lang.String getHoaDate() {
		return this.hoaDate;
	}

	public void setHoaDate(java.lang.String hoaDate) {
		this.hoaDate = hoaDate;
	}

	public java.lang.String getStatusCheckDelay() {
		return this.statusCheckDelay;
	}

	public void setStatusCheckDelay(java.lang.String statusCheckDelay) {
		this.statusCheckDelay = statusCheckDelay;
	}

	public java.lang.String getRepId() {
		return this.repId;
	}

	public void setRepId(java.lang.String repId) {
		this.repId = repId;
	}

	public java.lang.String getRspId() {
		return this.rspId;
	}

	public void setRspId(java.lang.String rspId) {
		this.rspId = rspId;
	}

	public java.lang.Boolean getHoaApproved() {
		return this.hoaApproved;
	}

	public void setHoaApproved(java.lang.Boolean hoaApproved) {
		this.hoaApproved = hoaApproved;
	}

	public OrderPermit(java.lang.String hoaDate, java.lang.String hoaAddress,
			java.lang.String hoaRepresentative, java.lang.String hoaGroup,
			java.lang.String repStatus, java.lang.String rspStatus,
			java.lang.String applicationStatus,
			com.myspace.permitting.Applicant applicant,
			java.lang.String statusCheckDelay, java.lang.String repId,
			java.lang.String rspId, java.lang.Boolean hoaApproved) {
		this.hoaDate = hoaDate;
		this.hoaAddress = hoaAddress;
		this.hoaRepresentative = hoaRepresentative;
		this.hoaGroup = hoaGroup;
		this.repStatus = repStatus;
		this.rspStatus = rspStatus;
		this.applicationStatus = applicationStatus;
		this.applicant = applicant;
		this.statusCheckDelay = statusCheckDelay;
		this.repId = repId;
		this.rspId = rspId;
		this.hoaApproved = hoaApproved;
	}

}